# Generated by Django 5.2.8 on 2025-11-19 08:23

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_id", models.CharField(max_length=128, unique=True)),
                ("item_name", models.CharField(db_index=True, max_length=1024)),
                ("section", models.CharField(db_index=True, max_length=64)),
                ("chunk_index", models.IntegerField()),
                ("text", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=384)),
            ],
        ),
        migrations.CreateModel(
            name="QAPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qa_id", models.CharField(max_length=128, unique=True)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("category", models.CharField(blank=True, max_length=256)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=384)),
            ],
        ),
    ]
