# Generated by Django 5.2.8 on 2025-12-04 01:29

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_id", models.CharField(max_length=128, unique=True)),
                ("item_name", models.CharField(db_index=True, max_length=1024)),
                ("section", models.CharField(db_index=True, max_length=64)),
                ("chunk_index", models.IntegerField()),
                ("text", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=384)),
            ],
        ),
        migrations.CreateModel(
            name="HealthFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(max_length=200, verbose_name="제조사"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=300, verbose_name="제품명"),
                ),
                (
                    "serve_use",
                    models.TextField(blank=True, null=True, verbose_name="섭취 방법"),
                ),
                (
                    "intake_hint",
                    models.TextField(blank=True, null=True, verbose_name="주의사항"),
                ),
                (
                    "main_function",
                    models.TextField(blank=True, null=True, verbose_name="기능성"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["manufacturer"], name="rag_healthf_manufac_82d041_idx"
                    ),
                    models.Index(
                        fields=["product_name"], name="rag_healthf_product_909b97_idx"
                    ),
                ],
                "unique_together": {("manufacturer", "product_name")},
            },
        ),
    ]
