# Generated by Django 4.2.26 on 2025-11-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chunk",
            name="chunk_id",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="chunk",
            name="item_name",
            field=models.CharField(db_index=True, max_length=512),
        ),
    ]
