# Generated by Django 4.2.26 on 2025-11-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0002_alter_chunk_chunk_id_alter_chunk_item_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chunk",
            name="item_name",
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
