# Generated by Django 4.2.26 on 2025-11-18 05:14

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0003_alter_chunk_item_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="QAPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qa_id", models.CharField(max_length=128, unique=True)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("category", models.CharField(blank=True, max_length=256)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=384)),
            ],
        ),
    ]
