# Generated by Django 5.2.7 on 2025-11-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("med_name", models.CharField(max_length=120, null=True)),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "meal_time",
                    models.CharField(
                        choices=[
                            ("before", "Before Meal"),
                            ("after", "After Meal"),
                            ("with", "With Meal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("taken", models.DateTimeField(blank=True, null=True)),
                ("use_alarm", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "plan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RegiHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "regi_type",
                    models.CharField(
                        max_length=50, verbose_name="등록 유형 (영양제/병원약)"
                    ),
                ),
                (
                    "iot_device_uuid",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="IoT 기기 UUID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="병명"
                    ),
                ),
                (
                    "issued_date",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="발행 날짜"
                    ),
                ),
                ("use_alarm", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "등록 이력",
                "verbose_name_plural": "등록 이력 목록",
                "db_table": "regihistory",
            },
        ),
    ]
