# Generated by Django 5.2.7 on 2025-11-19 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DrugInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(db_index=True, max_length=200)),
                ("efcy_qesitm", models.TextField(blank=True, null=True)),
                ("use_method_qesitm", models.TextField(blank=True, null=True)),
                ("atpn_warn_qesitm", models.TextField(blank=True, null=True)),
                ("atpn_qesitm", models.TextField(blank=True, null=True)),
                ("intrc_qesitm", models.TextField(blank=True, null=True)),
                ("se_qesitm", models.TextField(blank=True, null=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "medications_druginfo",
                "ordering": ["item_name"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                ("user", models.IntegerField(verbose_name="사용자 ID")),
                (
                    "prescription_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="처방전 ID"
                    ),
                ),
                (
                    "prescription_type",
                    models.CharField(
                        max_length=50, verbose_name="처방전 유형 (영양제/병원약)"
                    ),
                ),
                (
                    "disease_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="병명"
                    ),
                ),
                (
                    "issued_date",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="발행 날짜"
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 처방전",
                "verbose_name_plural": "사용자 처방전 목록",
                "db_table": "prescription",
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("med_name", models.CharField(max_length=120)),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "meal_time",
                    models.CharField(
                        choices=[
                            ("before", "Before Meal"),
                            ("after", "After Meal"),
                            ("with", "With Meal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("taken", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="medications.prescription",
                    ),
                ),
            ],
            options={
                "db_table": "plan",
                "ordering": ["-created_at"],
            },
        ),
    ]
