# Generated by Django 4.2.26 on 2025-12-01 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("medications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="regihistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자 ID",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="regihistory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="medications.regihistory",
            ),
        ),
    ]
