# Generated by Django 4.2.26 on 2025-11-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="use_alarm",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="regihistory",
            name="use_alarm",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="med_name",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
