# Generated by Django 5.2.7 on 2025-11-17 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="prescription",
            field=models.ForeignKey(
                db_column="prescription_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="medications.prescription",
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="prescription_id",
            field=models.BigAutoField(
                primary_key=True, serialize=False, verbose_name="처방전 ID"
            ),
        ),
    ]
