# Generated by Django 5.2.7 on 2025-11-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="regihistory",
            table="regihistory",
        ),
    ]
