# Generated by Django 5.2.7 on 2025-10-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicationhistory",
            name="status",
            field=models.CharField(
                choices=[("taken", "복용"), ("missed", "미복용")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="medicationhistory",
            name="taken_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
