# Generated by Django 5.2.7 on 2025-12-03 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0003_device_device_name_alter_device_unique_together"),
        ("medications", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regihistory",
            name="iot_device_uuid",
        ),
        migrations.AddField(
            model_name="regihistory",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="histories",
                to="iot.device",
                verbose_name="연동된 기기",
            ),
        ),
    ]
