# Generated by Django 5.2.8 on 2025-12-06 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="regihistory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="medications.regihistory",
            ),
        ),
        migrations.AlterField(
            model_name="regihistory",
            name="label",
            field=models.CharField(max_length=100, verbose_name="병명"),
        ),
    ]
