# Generated by Django 4.2.26 on 2025-11-17 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("medications", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("med_name", models.CharField(max_length=120)),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "meal_time",
                    models.CharField(
                        choices=[
                            ("before", "Before Meal"),
                            ("after", "After Meal"),
                            ("with", "With Meal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("taken", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "plan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                ("user", models.IntegerField(verbose_name="사용자 ID")),
                (
                    "prescription_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="처방전 ID"
                    ),
                ),
                (
                    "prescription_type",
                    models.CharField(
                        max_length=50, verbose_name="처방전 유형 (영양제/병원약)"
                    ),
                ),
                (
                    "disease_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="병명"
                    ),
                ),
                (
                    "issued_date",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="발행 날짜"
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 처방전",
                "verbose_name_plural": "사용자 처방전 목록",
                "db_table": "prescription",
            },
        ),
        migrations.RemoveField(
            model_name="medicationhistory",
            name="medication",
        ),
        migrations.RemoveField(
            model_name="medicationhistory",
            name="schedule",
        ),
        migrations.RemoveField(
            model_name="medicationhistory",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="medicationschedule",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="medicationschedule",
            name="medication",
        ),
        migrations.RemoveField(
            model_name="medicationschedule",
            name="user",
        ),
        migrations.DeleteModel(
            name="Medication",
        ),
        migrations.DeleteModel(
            name="MedicationHistory",
        ),
        migrations.DeleteModel(
            name="MedicationSchedule",
        ),
        migrations.AddField(
            model_name="plan",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="medications.prescription",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
