# Generated by Django 5.2.8 on 2025-11-24 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="regihistory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="medications.regihistory",
            ),
        ),
    ]
