# Generated by Django 5.2.7 on 2025-10-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0002_alter_medicationhistory_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_seq", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("efficacy", models.TextField(blank=True, null=True)),
                ("usage", models.TextField(blank=True, null=True)),
                ("caution", models.TextField(blank=True, null=True)),
                ("contraindication", models.TextField(blank=True, null=True)),
                ("interaction", models.TextField(blank=True, null=True)),
                ("side_effect", models.TextField(blank=True, null=True)),
                ("storage", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("open_date", models.DateField(blank=True, null=True)),
                ("update_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
