# Generated by Django 5.2.7 on 2025-11-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0002_alter_plan_prescription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
