# Generated by Django 5.2.8 on 2025-11-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0003_alter_plan_regihistory"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="regihistory",
            table="regihistory",
        ),
    ]
