# Generated by Django 5.2.7 on 2025-10-21 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0003_medicationinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicationschedule",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medicationschedule",
            name="is_taken",
            field=models.BooleanField(default=False),
        ),
    ]
