# Generated by Django 5.2.7 on 2025-11-17 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0003_alter_plan_created_at_alter_plan_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="prescription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="medications.prescription",
            ),
        ),
    ]
