# Generated by Django 4.2.26 on 2025-11-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0003_plan_prescription_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DrugInfo",
        ),
    ]
