# Generated by Django 4.2.26 on 2025-12-03 06:30

from django.db import migrations, models
import django.db.models.deletion
import iot.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_uuid",
                    models.CharField(
                        default=iot.models.generate_device_uuid,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "device_token",
                    models.CharField(
                        default=iot.models.generate_device_token, max_length=128
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_connected_at", models.DateTimeField(blank=True, null=True)),
                ("device_name", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "db_table": "iot_device",
            },
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_opened", models.BooleanField(default=False)),
                ("is_time", models.BooleanField(default=False)),
                ("collected_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("taken", "정상 복용"),
                            ("wrong", "오복용"),
                            ("missed", "미복용"),
                            ("none", "이벤트 아님"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_data",
                        to="iot.device",
                    ),
                ),
            ],
            options={
                "db_table": "iot_sensordata",
                "ordering": ["-collected_at"],
            },
        ),
    ]
