# Generated by Django 5.2.8 on 2025-11-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="status",
            field=models.CharField(
                choices=[
                    ("taken", "정상 복용"),
                    ("wrong", "오복용"),
                    ("missed", "미복용"),
                    ("none", "이벤트 아님"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
