<<<<<<<< HEAD:PythonProject/smart_med/iot/migrations/0003_alter_device_device_token_alter_device_device_uuid.py
# Generated by Django 5.2.8 on 2025-12-04 01:54
========
# Generated by Django 5.2.8 on 2025-12-04 01:38
>>>>>>>> origin/eun:PythonProject/smart_med/iot/migrations/0004_alter_device_device_token_alter_device_device_uuid.py

import iot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<<< HEAD:PythonProject/smart_med/iot/migrations/0003_alter_device_device_token_alter_device_device_uuid.py
        ("iot", "0002_initial"),
========
        ("iot", "0003_alter_device_device_token_alter_device_device_uuid"),
>>>>>>>> origin/eun:PythonProject/smart_med/iot/migrations/0004_alter_device_device_token_alter_device_device_uuid.py
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="device_token",
            field=models.CharField(
                default=iot.models.generate_device_token, max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_uuid",
            field=models.CharField(
                default=iot.models.generate_device_uuid, max_length=64, unique=True
            ),
        ),
    ]
