# Generated by Django 5.2.7 on 2025-11-26 10:17

import iot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="device_token",
            field=models.CharField(
                default=iot.models.generate_device_token, max_length=128
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="device_uuid",
            field=models.CharField(
                default=iot.models.generate_device_uuid, max_length=64, unique=True
            ),
        ),
    ]
