# Generated by Django 5.2.8 on 2025-12-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_device_device_name_alter_device_unique_together'),
        ('iot', '0004_device_device_token_device_device_uuid'),
    ]

    operations = [
    ]
