# Generated by Django 5.2.8 on 2025-12-03 05:39

import iot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_merge_20251203_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_token',
            field=models.CharField(default=iot.models.generate_device_token, max_length=128),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_uuid',
            field=models.CharField(default=iot.models.generate_device_uuid, max_length=64, unique=True),
        ),
    ]
