# Generated by Django 5.2.9 on 2026-01-06 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0003_alter_plan_regihistory_alter_regihistory_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('SUCCESS', '성공'), ('FAILED', '실패')], default='SUCCESS', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('regihistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.regihistory')),
            ],
        ),
    ]
