# Generated by Django 5.2.7 on 2025-11-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeartRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bpm", models.PositiveSmallIntegerField(verbose_name="심박수 (bpm)")),
                ("collected_at", models.DateTimeField(verbose_name="측정된 실제 시각")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="서버 수집 시각"
                    ),
                ),
            ],
            options={
                "verbose_name": "심박수 데이터",
                "verbose_name_plural": "심박수 데이터",
                "db_table": "health_heartrate",
                "ordering": ["-collected_at"],
            },
        ),
        migrations.CreateModel(
            name="StepCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("steps", models.PositiveIntegerField(verbose_name="걸음 수")),
                ("collected_at", models.DateTimeField(verbose_name="측정된 실제 시각")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="서버 수집 시각"
                    ),
                ),
            ],
            options={
                "verbose_name": "걸음 수 데이터",
                "verbose_name_plural": "걸음 수 데이터",
                "db_table": "health_stepcount",
                "ordering": ["-collected_at"],
            },
        ),
    ]
