# Generated by Django 4.2.26 on 2025-12-03 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="heartrate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="heart_rates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddField(
            model_name="dailystep",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_steps",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailystep",
            unique_together={("user", "date")},
        ),
    ]
