# Generated by Django 5.2.7 on 2025-11-10 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="heartrate",
            table="health_heartrate",
        ),
        migrations.AlterModelTable(
            name="stepcount",
            table="health_stepcount",
        ),
    ]
