# Generated by Django 4.2.26 on 2025-11-21 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("health", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                ("steps", models.PositiveIntegerField(verbose_name="하루 총 걸음 수")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="서버 저장 시각"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_steps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "일일 걸음 수 데이터",
                "verbose_name_plural": "일일 걸음 수 데이터",
                "db_table": "health_dailystep",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
