# Generated by Django 4.2.26 on 2025-11-24 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0003_dailystep"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StepCount",
        ),
    ]
