# Generated by Django 4.2.26 on 2025-12-05 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailVerification",
        ),
        migrations.DeleteModel(
            name="FcmToken",
        ),
    ]
