# Generated by Django 5.2.7 on 2025-11-19 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_fcm_token_alter_user_table_fcmtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="fcm_token",
        ),
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
        migrations.DeleteModel(
            name="FcmToken",
        ),
    ]
