# Generated by Django 5.2.7 on 2025-10-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_sensordata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensordata",
            name="medication",
        ),
        migrations.RemoveField(
            model_name="sensordata",
            name="user",
        ),
        migrations.RemoveField(
            model_name="sensordata",
            name="weight",
        ),
        migrations.AddField(
            model_name="sensordata",
            name="heart_rate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="is_opened",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="sensor_value",
            field=models.IntegerField(default=0),
        ),
    ]
